### PR TITLE
Updating to k8s 1.18 API.  Other minor cleanups

### PR DESCRIPTION
**Pull request by rrichardson**
This updates the source to the lates k8s go-client API.  It introduces a Context, as that is now a required part of the API.  It also offers some styling fixes.

### CODE REVIEW

**Comment by primeroz** [comment]
Hi @stefanprodan , is there a reason why this was never merged in ? 

We are hitting this issue on 1.16 cluster and we are planning to just fork the repo and merge this in for now ... we use this for consul on `loki` and `cortex` 

I can see https://github.com/grafana/loki/issues/2444 that mention that this consul-sidekick is depracted ... is it  ?

Thanks :)

**Review by bboreham — CHANGES_REQUESTED** [review]
Sorry I hadn't noticed I was requested to review this.

There is a `vendor` directory with the older Kubernetes client library; to make this change consistent either update that or remove it.

**Comment by bboreham** [comment]
@primeroz Weaveworks no longer runs this code; nowadays a StatefulSet is a better basis for something like Consul than a Deployment.
I will see if we can move it to weaveworks-experiments.

**Comment by primeroz** [comment]
@bboreham sure, we will move to the statefulset (or maybe hashicorp/consul-k8s ? ) as well but since we were using the jsonnet for LOKI and Cortex from grafanalabs i was sort of unsure what the right path was :) 

Thanks

**Review by bboreham — APPROVED** [review]
Looks ok

**Pull request merged**
